---
title: "bell_bonheure_pieper_edge"
output: html_document
date: "2022-11-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/Documents/GitHub/edgeproject") #zach setup link
#setwd("~/Desktop/MBAn/15.072 (Analytics Edge)/edgeproject-main") #guillaume setup link
#setwd("~/Desktop/MBAn/15.072 (Analytics Edge)/edgeproject-main") #paula setup link
library(caret)
library(ROCR)
library(dplyr)
```

```{r}
games_og = read.csv("match_scores.csv")
games_2024 = read.csv("all_games_2024.csv")
#games_r2_2021 = read.csv("Logistic 2021 Model/r2_2021_logistic.csv")
#games_r3_2021 = read.csv("r3_2021_logistic.csv")
#games_r4_2021 = read.csv("r4_2021_logistic.csv")
#games_r5_2021 = read.csv("r5_2021_logistic.csv")
#games_r1_2022 = read.csv("r1_2022.csv")
#games_r1_2021 = read.csv("r1_2021.csv")
#games_2023 = read.csv("all_games_2023.csv")
#teams_2023 = read.csv("teams2023.csv")
#teams_2022 = read.csv("team2022.csv")
teams = read.csv("team_data.csv")
teams.test = read.csv("team_data_21.csv")
teams_2024 = read.csv("teams2024.csv")
```

```{r}
organize <- function(games)
  games$confW = NA
  games$confL = NA
  games$G = NA
  games$W = NA
  games$ADJOE = NA
  games$ADJDE = NA
  games$BARTHAG = NA
  games$EFG_O = NA
  games$EFG_D = NA
  games$TOR = NA
  games$TORD = NA
  games$ORB = NA
  games$DRB = NA
  games$FTR = NA
  games$FTRD = NA
  games$X2P_O = NA
  games$X2P_D = NA
  games$X3P_O = NA
  games$X3P_D = NA
  games$X3PR = NA
  games$X3PRD = NA
  games$ADJ_T = NA
  games$WAB = NA
```

```{r}
#organize(games_r2_2021)
#organize(games_r3_2021)
#organize(games_r4_2021)
#organize(games_r5_2021)
#organize(games_r1_2022)
#organize(games_r1_2021)
organize(games_2024)
```

```{r}
update_table <- function(games, game_index, data){
  year <- games[game_index,"YEAR"]
  fav <- games[game_index,"HTEAM"]
  fav_seed <- games[game_index,"HSEED"]
  underdog <- games[game_index,"LTEAM"]
  underdog_seed <- games[game_index,"LSEED"]
  fav_index <- which(data$TEAM == fav & data$YEAR == year)
  underdog_index <- which(data$TEAM == underdog & data$YEAR == year)
  
  team1_index <- fav_index
  team2_index <- underdog_index
  
  #games[game_index,"confH"] = data[fav_index,"CONF"]
  #games[game_index,"confL"] = data[underdog_index,"CONF"]
  games[game_index,"G"] = data[team1_index,"G"] - data[team2_index,"G"]
  games[game_index,"W"] = data[team1_index,"W"] - data[team2_index,"W"]
  games[game_index,"ADJOE"] = data[team1_index,"ADJOE"] - data[team2_index,"ADJOE"]
  games[game_index,"ADJDE"] = data[team1_index,"ADJDE"] - data[team2_index,"ADJDE"]
  games[game_index,"BARTHAG"] = data[team1_index,"BARTHAG"] - data[team2_index,"BARTHAG"]
  games[game_index,"EFG_O"] = data[team1_index,"EFG_O"] - data[team2_index,"EFG_O"]
  games[game_index,"EFG_D"] = data[team1_index,"EFG_D"] - data[team2_index,"EFG_D"]
  games[game_index,"TOR"] = data[team1_index,"TOR"] - data[team2_index,"TOR"]
  games[game_index,"TORD"] = data[team1_index,"TORD"] - data[team2_index,"TORD"]
  games[game_index,"ORB"] = data[team1_index,"ORB"] - data[team2_index,"ORB"]
  games[game_index,"DRB"] = data[team1_index,"DRB"] - data[team2_index,"DRB"]
  games[game_index,"FTR"] = data[team1_index,"FTR"] - data[team2_index,"FTR"]
  games[game_index,"FTRD"] = data[team1_index,"FTRD"] - data[team2_index,"FTRD"]
  games[game_index,"X2P_O"] = data[team1_index,"X2P_O"] - data[team2_index,"X2P_O"]
  games[game_index,"X2P_D"] = data[team1_index,"X2P_D"] - data[team2_index,"X2P_D"]
  games[game_index,"X3P_O"] = data[team1_index,"X3P_O"] - data[team2_index,"X3P_O"]
  games[game_index,"X3P_D"] = data[team1_index,"X3P_D"] - data[team2_index,"X3P_D"]
  games[game_index,"X3PR"] = data[team1_index,"X3PR"] - data[team2_index,"X3PR"]
  games[game_index,"X3PRD"] = data[team1_index,"X3PRD"] - data[team2_index,"X3PRD"]
  games[game_index,"ADJ_T"] = data[team1_index,"ADJ_T"] - data[team2_index,"ADJ_T"]
  games[game_index,"WAB"] = data[team1_index,"WAB"] - data[team2_index,"WAB"]
  
  return(games)
}
  
```

```{r}
for (x in 1:16){
  games_r2_2021 <- update_table(games_r2_2021,x,teams.test)
}
```

```{r}
for (x in 1:8){
  games_r3_2021 <- update_table(games_r3_2021,x,teams.test)
}
```

```{r}
for (x in 1:4){
  games_r4_2021 <- update_table(games_r4_2021,x,teams.test)
}
```

```{r}
for (x in 1:4){
  games_r5_2021 <- update_table(games_r5_2021,x,teams.test)
}
```

```{r}
for (x in 1:4){
  games_r5_2021 <- update_table(games_r5_2021,x,teams.test)
}
```

```{r}
for (x in 1:32){
  games_r1_2022 <- update_table(games_r1_2022,x,teams_2022)
}
```

```{r}
for (x in 1:31){
  games_r1_2021 <- update_table(games_r1_2021,x,teams.test)
}
```

```{r}
for (x in 1:2278){
  games_2024 <- update_table(games_2024,x,teams_2024)
}
```

```{r}
#write.csv(games_r2_2021, "r2games_log.csv")
#write.csv(games_r3_2021, "r3games_log.csv")
#write.csv(games_r4_2021, "r4games_log.csv")
#write.csv(games_r5_2021, "r5games_log.csv")
#write.csv(games_r1_2022, "r1games_2022.csv")
#write.csv(games_r1_2021, "r1games_2021.csv")
write.csv(games_2024, "games_2024.csv")
```

