---
title: "LinearRegression"
output: html_document
date: "2022-11-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/Documents/GitHub/edgeproject") #for zach
games = read.csv("game_diff_upd.csv")
games = subset(games, select=-c(HTEAM,LTEAM,HSCORE,LSCORE,UPSET))
games.train <- games[games$YEAR < 2019, ]
games.test <- games[games$YEAR >= 2019, ]
```

```{r}
library(ggcorrplot)
ggcorrplot(cor(games.train))
```

```{r}
lin_reg = lm(SCORE_DIFF~. -HSEED -LSEED -ADJOE -ADJDE -YEAR -ROUND -EFG_D -EFG_O -BARTHAG, data=games.train)
summary(lin_reg)
```

```{r}
lin.mean <- mean(games.train$SCORE_DIFF)
lin_SST <- sum((lin.mean - games.test$SCORE_DIFF)^2)

lin_pred <- predict(lin_reg, newdata = games.test)
lin_SSE <- sum((lin_pred - games.test$SCORE_DIFF)^2)
lin_osr <- 1 - lin_SSE/lin_SST


```

```{r}
#games_full = read.csv("upset_data.csv")
games_full = read.csv("full_22_data.csv")
games2 = subset(games_full, select=-c(X,HTEAM,LTEAM,HSCORE,LSCORE,SCORE_DIFF,confW,confL,WAB))
games2.train <- games2[games2$YEAR < 2019, ]
games2.test <- games2[games2$YEAR >= 2019, ]
#model.r1 <- games2[games2$YEAR == 2021, ]
#model.r1 <- model.r1[model.r1$ROUND == 1, ]
#model.r1_a = subset(model.r1, select=-c(UPSET))

#model.r2 <- read.csv("Logistic 2021 Model/r2games_log.csv")
#model.r2_a = subset(model.r2, select=-c(X,HTEAM,LTEAM,WAB,confH,confL))

#model.r3 <- read.csv("Logistic 2021 Model/r3games_log.csv")
#model.r3_a = subset(model.r3, select=-c(X,HTEAM,LTEAM,WAB,confH,confL))

#model.r4 <- read.csv("Logistic 2021 Model/r4games_log.csv")
#model.r4_a = subset(model.r4, select=-c(X,HTEAM,LTEAM,WAB,confH,confL))

#model.r5 <- read.csv("Logistic 2021 Model/r5games_log.csv")
#model.r5_a = subset(model.r5, select=-c(X,HTEAM,LTEAM,WAB,confH,confL))

model.r1_22 <- read.csv("r1games_2022.csv")
model.r1_22_a = subset(model.r1_22, select=-c(X,HTEAM,LTEAM,WAB))

#model.r1_21 <- read.csv("r1games_2021.csv")
#model.r1_21_a = subset(model.r1_21, select=-c(X,HTEAM,LTEAM,WAB))

model.r23 <- read.csv("games_2023.csv")
model.r23_a = subset(model.r23, select=-c(X,HTEAM,LTEAM,WAB))
```

```{r}
log_reg = glm(upset~. -HSEED -LSEED -ADJOE -ADJDE -YEAR -ROUND -EFG_D -EFG_O -BARTHAG, data=games2, family="binomial")

#log_reg = glm(upset~. -HSEED -LSEED -confW -confL -ADJOE -ADJDE -YEAR -ROUND -EFG_D -EFG_O -BARTHAG, data=games2, family="binomial")
#log_reg = glm(UPSET~. -HSEED -LSEED -YEAR -ROUND, data=games2.train, family="binomial")
summary(log_reg)
```

```{r}
log_pred <- predict(log_reg, newdata = games2.test)
odds <- exp(log_pred)
prob <- odds/(1+odds)
prob
```

```{r}
threshPred <- (prob > 0.5)
confusion.matrix = table(games2.test$UPSET, threshPred)
confusion.matrix
```

```{r}
r1_log_pred <- predict(log_reg, newdata = model.r1_a)
r1odds <- exp(r1_log_pred)
r1prob <- r1odds/(1+r1odds)
r1prob
```


```{r}
r2_log_pred <- predict(log_reg, newdata = model.r2_a)
r2odds <- exp(r2_log_pred)
r2prob <- r2odds/(1+r2odds)
r2prob
```

```{r}
r3_log_pred <- predict(log_reg, newdata = model.r3_a)
r3odds <- exp(r3_log_pred)
r3prob <- r3odds/(1+r3odds)
r3prob
```

```{r}
r4_log_pred <- predict(log_reg, newdata = model.r4_a)
r4odds <- exp(r4_log_pred)
r4prob <- r4odds/(1+r4odds)
r4prob
```

```{r}
r5_log_pred <- predict(log_reg, newdata = model.r5_a)
r5odds <- exp(r5_log_pred)
r5prob <- r5odds/(1+r5odds)
r5prob
```

```{r}
r12_log_pred <- predict(log_reg, newdata = model.r1_22_a)
r12odds <- exp(r12_log_pred)
r12prob <- r12odds/(1+r12odds)
r12prob
```

```{r}
r11_log_pred <- predict(log_reg, newdata = model.r1_21_a)
r11odds <- exp(r11_log_pred)
r11prob <- r11odds/(1+r11odds)
r11prob
```

```{r}
r23_log_pred <- predict(log_reg, newdata = model.r23_a)
r23odds <- exp(r23_log_pred)
r23prob <- r23odds/(1+r23odds)
r23prob
```

```{r}
df23prob <- data.frame(r23prob) 
write.csv(df23prob, 'upset_prob_w22.csv', row.names=FALSE)
```